name: Android CI

on: push

jobs:
  build:
    name: Android Debug Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Build Project
        run: ./gradlew :app:assembleDebug

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --tests com.dwards.a5edpockethelper.unitTests.CharacterListAdapterTest |
            ./gradlew testDebugUnitTest --tests com.dwards.a5edpockethelper.unitTests.ConverterTest |
            ./gradlew testDebugUnitTest --tests com.dwards.a5edpockethelper.unitTests.ConverterTest

      - name: Run UI Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 23
          target: default
          arch: x86
          profile: Nexus 6
        - run: ./gradlew testDebugUnitTest --tests com.dwards.a5edpockethelper.integretionTest.ModalDialogs
